[package]
name = "swiftsc-driver"
version = "0.1.0"
edition = "2021"

[dependencies]
swiftsc-frontend = { path = "../frontend" }
swiftsc-backend = { path = "../backend" }
clap = { version = "4.4", features = ["derive"] }
anyhow = "1.0"
